version: '3.3'

networks:
  film:
    external:
      name: filmspersons_default



services:
  nginx:
    build: .
    container_name: apigateway
    hostname: apigateway
    image: apigateway
    ports:
      - 80:80
    networks:
      - film